### ISSUE TITLE
dav1d upgrade

### ISSUE THREAD

**Issue by iDNA420** [USBhost/MX_FFmpeg#10]
@USBhost 
91e9799cdc4bc6b022bab8415562500a0f33745a will not actually upgrade the dav1d library used. In the config-ffmpeg.sh script, only the dav1d header files are referenced. The only external library passed to the linker is libmxutil. So, I believe, dav1d and other dependency library symbols are resolved from libmxutil. If you use header files from newer dav1d versions, you will end up with a broken FFmpeg library as FFmpeg will be built for a newer version of the dav1d library but the actual one resolved through libmxutil will be the older one. That's why it's crashing. Even if it works, you will not get any benifits of the newer dav1d library as the underlaying library is still older one.

I think the better way to upgrade dav1d library is to build it as a static library and pass appropriate linker flags so that will be a part of ffmpeg library.

**Comment by USBhost** [comment]
Ahh I see.
