### ISSUE TITLE
MXPlayer 1.41.2 Custom Codec is out

### ISSUE THREAD

**Issue by vivek-5131** [USBhost/MX_FFmpeg#11]
admin can you make 1.41.2 aio file I know I can rename the file of 1.35.0 to 1.41.2 but if possible

**Comment by USBhost** [comment]
thanks for the update. As I use the pro version I dont know about these updates lol, just keep opening issues for when updates hit the free version.

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.41.2 done sorry for the delay
