### ISSUE TITLE
A12 Armv8 Neon

### ISSUE THREAD

**Issue by xxmcvapourxx** [USBhost/MX_FFmpeg#13]
Can you build A12 Armv8 Neon. i've tested each of the zips it says "cant find custom codec please use 1.35.0 Armv8 Neon" i have tested each one of the neons same issue

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.35.0 this one doesn't work?

**Comment by xxmcvapourxx** [comment]
My bad it was so.neon64.1.35.0 i was trying the other neons all working fine now thanks dude
