### ISSUE TITLE
Mx player freeze upon updating custom codec

### ISSUE THREAD

**Issue by Saqibhanif2004** [USBhost/MX_FFmpeg#14]
I have trying to update mx player version 1.44 custom codecs. When i start mx player it shows option that new codecs find update . When i click on update it freeze and when i close app and start again it show some components are curropted.pleaae resolve my issue.because i do not use any ither media player
![Screenshot_20220309_233732](https://user-images.githubusercontent.com/17958225/157508844-4d9117dc-7c69-49fd-a315-293d6574f8d0.jpg)

**Comment by USBhost** [comment]
Try the latest one. https://github.com/USBhost/MX_FFmpeg/releases/tag/1.44.0
