### ISSUE TITLE
MX Pro Not Recognizing New Codec

### ISSUE THREAD

**Issue by rjm831** [USBhost/MX_FFmpeg#16]
Have MX Player Pro installed on a Samsung Tab A7 (android 11).  It won't recognize (install) any of the new 1.44.0 codecs.  Is the problem on my end or is it with MX?

**Comment by USBhost** [comment]
Use [1.41.2](https://github.com/USBhost/MX_FFmpeg/releases/tag/1.41.2)

MX player free is like an update ahead.
