### ISSUE TITLE
Custom codec v1. 44.0 does not work with MX Player Pro v1.46.10

### ISSUE THREAD

**Issue by Waqqars987** [USBhost/MX_FFmpeg#17]
Hi,

MX Player Pro v1.46.10 got released and since then the custom codec v1.44.0 has stopped working.

Please provide an updated one.

Thanks.

**Comment by i5lee8bit** [comment]
Maybe try loading the codec again? Or try the aio version if you haven't already? It definitely works for me on multiple devices. v1.46.10 (and yes, Pro version MX Player), using codec pack aio 1.44.0 on:

Samsung Galaxy Tab S7 Plus
Google Pixel 4 XL
Google Pixel 4

Working across all devices here.

**Comment by dcbishop** [comment]
I don't get any EAC3 audio on 1.46. It suppresses the error message though. I tried AIO version

**Comment by Waqqars987** [comment]
> Maybe try loading the codec again? Or try the aio version if you haven't already? It definitely works for me on multiple devices. v1.46.10 (and yes, Pro version MX Player), using codec pack aio 1.44.0 on:
> 
> Samsung Galaxy Tab S7 Plus Google Pixel 4 XL Google Pixel 4
> 
> Working across all devices here.

Tried to load AIO version of 1.44, getting the following error:

"Can't find custom codec. Please use version 1.44.0 ARMv8 NEON codec."

Everything was working fine tll the previous version of PRO.

**Comment by ShocWave** [comment]
Same problem, I cannot load the codec on MX Player Pro on my Xiaomi Mi Mix 3.
"Can't find custom codec. Please use version 1.41.2. ARMv8 NEON codec"

**Comment by USBhost** [comment]
> Same problem, I cannot load the codec on MX Player Pro on my Xiaomi Mi Mix 3. "Can't find custom codec. Please use version 1.41.2. ARMv8 NEON codec"

Then use the older one. Not 1.44.0

**Comment by USBhost** [comment]
> > Maybe try loading the codec again? Or try the aio version if you haven't already? It definitely works for me on multiple devices. v1.46.10 (and yes, Pro version MX Player), using codec pack aio 1.44.0 on:
> > Samsung Galaxy Tab S7 Plus Google Pixel 4 XL Google Pixel 4
> > Working across all devices here.
> 
> Tried to load AIO version of 1.44, getting the following error:
> 
> "Can't find custom codec. Please use version 1.44.0 ARMv8 NEON codec."
> 
> Everything was working fine till the previous version of PRO.

Use libffmpeg.mx.so.neon64.1.44.0

**Comment by USBhost** [comment]
> I don't get any EAC3 audio on 1.46 PRO or non-pro. Loading the codec suppresses the error message though. I tried AIO version.
> 
> I'm on a Pixel 5 XL.

Your using libffmpeg.mx.so.neon64.1.44.0 correct?
EAC3 SW working on my OnePlus 8T
