### ISSUE TITLE
update dav1d and ffmpeg? 

### ISSUE THREAD

**Issue by movy** [USBhost/MX_FFmpeg#19]
Hello,
Thanks for this package!
I am experiencing some weird issues while using these codecs with MX player on my projector (Xgimi Z6X) with audio channel mapping in DTS mode -- center and right channels are swapped, left-read is gone completely etc + consistent audio delay. None of these issues are present with Dolby encoded material.

I was wondering whether it's due to some old bugs in ffmpeg and dav1d? I can see this codec package uses fairly old versions, so I tried building my own with updated ones, but ffmpeg fails to configure with:

`dav1d >= 0.5.0 not found using pkg-config`

(Actual dav1d in my system is 1.0.0). 

I tried building dav1d statically, installing from packages etc -- no avail. So after couple hours of different failing paths I gave up.
Building on Ubuntu 22, using `android-ndk-r21e` as some tools used in your build process were removed from more recent NDKs.

Maybe you can update all versions to make a more modern codec pack? Thanks so much for your time!

**Comment by USBhost** [comment]
I believe this is out of my hands cuz I tried before and turns out the "dav1d" we build is only for the headers. We are not actually building the source.

**Comment by movy** [comment]
That's a bummer, but thanks for looking into it. Fingers crossed it can be updated somehow soon.
