### ISSUE TITLE
Awesome Work You have done !!!. Could you help me to add this codec in Exoplayer 

### ISSUE THREAD

**Issue by darwinvtomy** [USBhost/MX_FFmpeg#2]
I want to enable Passthrough in  Exoplayer for rk3368 based android box .Your code supports the passthrough in our box please give me a solution to use it in  exoplayer

**Comment by USBhost** [comment]
This is not my work. I'm only building from source.

**Comment by darwinvtomy** [comment]
Thanks for replaying
