### ISSUE TITLE
Mx codec update 1.49.0

### ISSUE THREAD

**Issue by moaztarek63** [USBhost/MX_FFmpeg#20]
Play store updated and 1.44.0 is not valid it's updated to 1.49.0

**Comment by USBhost** [comment]
The updated source is not up yet.

**Comment by USBhost** [comment]
I'm not seeing the new source

**Comment by moaztarek63** [comment]
Mx app says it's updated to 1.49.0 I don't if there is source update or something.. just notify

**Comment by USBhost** [comment]
Does renaming the codec to what expects works for you or does it just crash?

**Comment by moaztarek63** [comment]
Don't accept the renamed it crash and still saying can't find 1.49.0 custom codec

**Comment by moaztarek63** [comment]
I'm going downgrade just notify the update

**Comment by mujtaba-droid** [comment]
![Screenshot_20220912-231940](https://user-images.githubusercontent.com/113382030/189727691-c96dfa50-525a-47bc-9263-5afb34f40e4e.png)

**Comment by mujtaba-droid** [comment]
Help please.

**Comment by mujtaba-droid** [comment]
How do I change the codec? Before it was working fine but now it is showing this error.

**Comment by moaztarek63** [comment]
Remove the exciting mx app and download 1.48.12 from any trust source (APK mirror - uptodown) untill the codec update been released

**Comment by USBhost** [comment]
Well I talked to support and they told me it'll be out soon™.

**Comment by ottokang** [comment]
They just release 1.49.0 ffmpeg codec: [https://github.com/MXVideoPlayer/MX-FFmpeg/releases/tag/v1.49.0](https://github.com/MXVideoPlayer/MX-FFmpeg/releases/tag/v1.49.0)

**Comment by USBhost** [comment]
> MX Player just release 1.49.0 ffmpeg codec: https://github.com/MXVideoPlayer/MX-FFmpeg/releases/tag/v1.49.0

thanks and currently building it.

**Comment by VasilisKos** [comment]
MX Player Pro is still 1.46.10, and doesn't recognize codec 1.49. Only 1.44.
