### ISSUE TITLE
Cannot update custom codec to version 49

### ISSUE THREAD

**Issue by dvdvideo1234** [USBhost/MX_FFmpeg#21]
Hi,

No matter what I do I cannot update my custom codec past version 44. My Note 4 is not accepting the higher versions and I am unable to play HEVC. I am running the payed version of MX player via Google play store. Do you have any idea why this happens and how can I overcome this issue. Please do not tell me to buy a new phone as it will be unacceptable!

**Comment by aeu99184** [comment]
Same issue here with Google tv

**Comment by aeu99184** [comment]
Issue solved by changing mxplayers access folder settings. Thx

**Comment by dvdvideo1234** [comment]
To resolve the issue:
1. Open settings and select `List`
2. Go to scan and click on `Folders`
3. Click `Add` and Add your folder: `/storage/0000-0000/Install/Codecs`
4. Click `Back`, `Back` then `Decoder`
5. Click `Custom Codec` and point it to the file in point `(3)`
6. Restart the player to accept codec
