### ISSUE TITLE
Nvidia Shield TV does not recognize the mx_aio.zip

### ISSUE THREAD

**Issue by git-dimiz** [USBhost/MX_FFmpeg#27]
Hi, 

I'm using the `MX Player Pro` in version `1.51.8 ARMv7 Neon`. It seems it does not recognize the zip file which I've put into the Downloads folder. Am I doing something wrong there?

I tested the same on my android phone and it works fine.

**Comment by llllVIIII** [comment]
I already did that. The MX Player App has the file system permissions granted. Just don't understand why it won't recognize the zip file.

**Comment by USBhost** [comment]
Use the none 64 neon version.
