### ISSUE TITLE
Clarification on the meaning of these "custom" codecs

### ISSUE THREAD

**Issue by VegethB** [USBhost/MX_FFmpeg#28]
I would like to understand one thing:
Let's take the Teclast M40 Pro as an example...
The tablet is equipped with Android 12 stripped down to the bone. To levels where there are NO HW codecs even for h263 and VP9.
On MXPlayer, in HW+ it does not give me HW acceleration grey text on anything.
On Emby, it tells you that the render in use is FFMPEG (normaly is ExoPlayer2).
So, these custom codecs take advantage of HW acceleration by using commands like "`ffmpeg.exe -hwaccel cuda -hwaccel_output_format cuda"` but for Mali ARM GPUs and would go to solve the problem of no codecs at all in the android system? 
Or are they interfacing systems with the codecs already installed in Android?
Thanks

**Comment by USBhost** [comment]
These just enable what MX disable themselves. So I can't support you there. Sorry.
