### ISSUE TITLE
mx player 1.86.0 cannot recognize codecs

### ISSUE THREAD

**Issue by jhlcw** [USBhost/MX_FFmpeg#31]
Please solve this problem.

**Comment by PatBEL71** [comment]
MX player Pro 1.86.0 with 1.49.0 (ARMV7) on my chromecast with google tv (ccwgtv) also stopped working yesterday.
when the episode I was watching was done and I started the next episode, The "EAC3 not supported" Error shows up out of nowhere.
I tried to apply the codec again but it's no go!

**Comment by fawzib** [comment]
application is pretty useless without those codecs, what is the reason they are not part of the application by default?

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.86.0

**Comment by jhlcw** [comment]
> https://github.com/USBhost/MX_FFmpeg/releases/tag/1.86.0

😁😁😁
