### ISSUE TITLE
New mx player 1.86.0 version can't recognize old codec

### ISSUE THREAD

**Issue by rahulsinha23** [USBhost/MX_FFmpeg#32]
New mx player 1.86.0 version can't recognize old codec. Please fix it asap.

**Comment by USBhost** [comment]
The MX guys has not updated their source yet. See here https://github.com/MXVideoPlayer/MX-FFmpeg

**Comment by rahulsinha23** [comment]
> The MX guys has not updated their source yet. See here https://github.com/MXVideoPlayer/MX-FFmpeg

How to contact him?

**Comment by Mridumoloy** [comment]
> The MX guys has not updated their source yet. See here https://github.com/MXVideoPlayer/MX-FFmpeg

It just got just updated now like some 20-25 minutes ago. Could you kindly update the codecs now?

**Comment by rahulsinha23** [comment]
They not updated new version of codec

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.86.0
