### ISSUE TITLE
Dev is gone from here but new 1.86.0 codec desperately needed

### ISSUE THREAD

**Issue by Chesshur** [USBhost/MX_FFmpeg#33]
The old codec no longer works with mx player 1.86.0 which updated recently. The developer hasn't been here in over 2 years. Now, the app is useless without the codec!

**Comment by TDKRWolverine** [comment]
Without it as you say it's pretty useless...I have had to go back to VLC which does work for EAC3 for example

**Comment by zip6como** [comment]
If someone is able to find out what is causing the issue, please tell me.
I **might** be able to create a fix. But I need to know why the custom codec isn't working.
Any useful logs would be appreciated.

**Comment by USBhost** [comment]
Remember I can't update the source as it's not fully Open-Source. I need to wait for MX to update their source.

**Comment by fawzib** [comment]
i assume you are referring to this https://github.com/MXVideoPlayer/MX-FFmpeg

**Comment by TDKRWolverine** [comment]
> Remember I can't update the source as it's not fully Open-Source. I need to wait for MX to update their source.

Yeah. I understand that. It is frustrating that's all. I know the pro isn't that expensive and I've had it for years but I just love the UI of MX compared to anything else.

**Comment by zQueal** [comment]
Downgrading from the most current version to the penultimate version will temporarily fix this issue until the codec are released.

Disable automatic updates in the Play store for MX Player otherwise the new version will just reinstall.

**Comment by TDKRWolverine** [comment]
How can you downgrade though when the play store will only have the latest release won't it?
Thanks

**Comment by gshacklebolt** [comment]
Download from some external vendor. There are many trustworthy apk providers like apkmirror

**Comment by TDKRWolverine** [comment]
> Download from some external vendor. There are many trustworthy apk providers like apkmirror

Thank you

So 1.85.8 should work. 

Appreciate the help and guidance to that site 👌🏻

**Comment by Mridumoloy** [comment]
> Remember I can't update the source as it's not fully Open-Source. I need to wait for MX to update their source.

Source Code was updated recently. Please update the codecs.
Thanks

**Comment by atnoir** [comment]
> Remember I can't update the source as it's not fully Open-Source. I need to wait for MX to update their source.

https://github.com/MXVideoPlayer/MX-FFmpeg/commit/afa58d65a89dd288232e41bf5d844fe64ee48796

It just updates ffmpeg sources for 1.86.x, please kindly update the codec. Thank you.

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.86.0
