### ISSUE TITLE
Can't find custom codec. Please use version 1.49.0 ARMv8 NEON codec.

### ISSUE THREAD

**Issue by atnoir** [USBhost/MX_FFmpeg#34]
I've successfully added custom codec for MX player pro 1.86.0 from [this link](https://github.com/daugustin/MX-FFmpeg/releases), but when I download your codec and apply, it says "Can't find custom codec. Please use version 1.49.0 ARMv8 NEON codec."

**Comment by USBhost** [comment]
Use the older version https://github.com/USBhost/MX_FFmpeg/releases/tag/1.49.0

**Comment by atnoir** [comment]
> Use the older version https://github.com/USBhost/MX_FFmpeg/releases/tag/1.49.0

But your older version doesn't work with MX player pro 1.86.0

**Comment by CzBiX** [comment]
Download the so file in 1.86.0 version, then rename it to 1.49.0.
Now it can be loaded.

**Comment by USBhost** [comment]
rename the the 86 back to 49.

I'm going to update the file names.

**Comment by USBhost** [comment]
Fixed
