### ISSUE TITLE
Can't find custom codec. Please use version 1.87.0 ARMv8 NEON codec.

### ISSUE THREAD

**Issue by clevercjl** [USBhost/MX_FFmpeg#36]
MX Player 1.87.0 can't recognize libffmpeg.mx.so.neon64.1.49.0.

I tried to rename the file to "libffmpeg.mx.so.neon64.1.87.0", but it said "Component files are corrupted or Android internal modules are not compatible with current version of MX Player ."

**Comment by satyakrishna48** [comment]
Yes same

**Comment by tw004619** [comment]
The same please help

**Comment by Faiyyaz** [comment]
Same issue

**Comment by USBhost** [comment]
Maybe they updated the source code, however... Their source hasn't updated.

**Comment by mauriicio3** [comment]
Same here

**Comment by neroxyr** [comment]
same here

**Comment by clevercjl** [comment]
https://github.com/MXVideoPlayer/MX-FFmpeg/releases/tag/v1.87.0
The source code has been updated

**Comment by satyakrishna48** [comment]
> https://github.com/MXVideoPlayer/MX-FFmpeg/releases/tag/v1.87.0 The source code has been updated

Not working

**Comment by clevercjl** [comment]
This is the source code of the codec, not the integrated codec, it doesn't work

**Comment by neroxyr** [comment]
tried, not working either

**Comment by mauriicio3** [comment]
thanks!

Em 21 de novembro de 2024 20:18:46 UTC, owocado ***@***.***> escreveu:
>> https://github.com/MXVideoPlayer/MX-FFmpeg/releases/tag/v1.87.0 The source code has been updated
>
>I tried building the new static binary from this updated source code for `arm64` and it works, the app loaded the codec.
>For the app to recognise the codec, I had to rename the built binary to `libffmpeg.mx.so.neon64.1.87`
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/USBhost/MX_FFmpeg/issues/36#issuecomment-2492186038
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Maurício

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.87.0

**Comment by Neon329** [comment]
I still cannot install the new version 
![Screenshot_2024-11-23-18-23-20-31_010925bd39fdc4bfa0e99fa1d4c2b790](https://github.com/user-attachments/assets/773831a3-203b-46ee-b9e0-2df54e45064a)
