### ISSUE TITLE
Can't use HW+ decoder

### ISSUE THREAD

**Issue by MESWEB** [USBhost/MX_FFmpeg#5]
After load latest custom codec mx_aio.zip or mx_neon.zip I can't use HW+ decoder for:
File format .m2ts BluRay copy on USB HDD Drive
Video Stream, SMPTE VC-1, Profile "Advanced", 1920x1080, 23.97602

**Comment by USBhost** [comment]
I do not believe this has anything to do with me. Contact the MX Player guys.
