### ISSUE TITLE
Update to 1.32

### ISSUE THREAD

**Issue by FlyingRaijin07** [USBhost/MX_FFmpeg#6]
This 1.25 version is not accepted by MX player.
I need Armv8 Neon 1.32 .
So please try n give me this.

**Comment by FlyingRaijin07** [comment]
I have a Snapdragon 855 chip on OnePlus 7.

**Comment by QAQrz** [comment]
Kirin 990 on HUAWEI Mate 30 Pro needs Armv8 Neon 1.32, too.

**Comment by USBhost** [comment]
Thanks for the report. Yep it should be out soonish today.

**Comment by USBhost** [comment]
Will look into it later today

**Comment by USBhost** [comment]
https://github.com/USBhost/MX_FFmpeg/releases/tag/1.32.0

reopen this if they do not work.

**Comment by QAQrz** [comment]
It works, tks.
