### ISSUE TITLE
1.35.0 Codec Request

### ISSUE THREAD

**Issue by Shumzy55** [USBhost/MX_FFmpeg#8]
Hi,

Can you please upload the latest Custom Codecs for Mx Player 1.35.1.

Also I had issues with the last Custom Codec you uploaded 1.32.0 (armv7a) with the embedded subtitles not showing up in the videos but the external subtitles worked.

Thanks

**Comment by changlish76** [comment]
![MXsubtitle](https://user-images.githubusercontent.com/80670676/111115371-e2869400-853a-11eb-9e3c-9a6fcb730e47.png)

**Comment by Shumzy55** [comment]
Hello,

For the 1.32.0 codec issue I was referring back to when I used this on Mx Player 1.32.5, (Also all the custom codecs I have downloaded have officially come from your forum, I have not renamed or modified any of them) but now I have updated Mx Player to 1.35.1 I have been notified in the app that my custom codec (1.32.0) is outdated and that I need to use an updated codec for it to work

So that is why I requested if you could upload the latest codec onto your forum for Mx Player 1.35.1.

Thanks,

**Comment by USBhost** [comment]
The new source is not out yet. It's still 1.32

**Comment by Shumzy55** [comment]
I'm not sure if you meant that the 1.35.1 custom codec is not available just yet..but their website https://mx.j2inter.com have just recently uploaded the latest version of Mx Player (1.35.1) here https://mx.j2inter.com/download.

**Comment by USBhost** [comment]
> I'm not sure if you meant that the 1.35.1 custom codec is not available just yet..but their website https://mx.j2inter.com have just recently uploaded the latest version of Mx Player (1.35.1) here https://mx.j2inter.com/download.

![Screenshot_20210315-082125](https://user-images.githubusercontent.com/7269941/111177522-8ab25200-8567-11eb-80df-ec35b893fd70.jpg)

**Comment by Shumzy55** [comment]
Oh ok, thanks for clarifying this

Guess I'll just wait until it's available.

**Comment by Shumzy55** [comment]
Hi,

The new open-source code for Mx Player 1.35.2 is now out. https://mx.j2inter.com/download

**Comment by dotjaz** [comment]
Any chance to update dav1d to 0.8.x? Thank you https://github.com/videolan/dav1d

**Comment by iDNA420** [comment]
> Any chance to update dav1d to 0.8.x? Thank you https://github.com/videolan/dav1d

dav1d is not a part of this build system. I guess, they ship it separately with the app.

**Comment by USBhost** [comment]
Will update it Friday evening. Apologies for the delay

**Comment by Shumzy55** [comment]
That's ok, thanks for letting us know.

**Comment by USBhost** [comment]
@dotjaz try this one out https://github.com/USBhost/MX_FFmpeg/releases/tag/1.35.0_test

**Comment by samqplays** [comment]
@USBhost It's my first time here. I was too lazy how to compile the 1.35.0 source to arm64 binary, for my MX Player Pro 1.32.8 (that I've only used) which is compatible with the 1.35.0 codec.

By the way before you compiling it, is there any chance to update all components (ffmpeg, dav1d, libopus, etc.) to latest version or anything higher version as possible for **1.35.0**? I was noob how to do it, unless you help me.

**Comment by USBhost** [comment]
Sadly I do not believe we can. I tried in the past and well it didn't work out so well. Also MX player has alot of custom patches making any kind of porting near impossible for my expertise.

**Comment by samqplays** [comment]
> Sadly I do not believe we can. I tried in the past and well it didn't work out so well. Also MX player has alot of custom patches and closed source binary blobs making any kind of porting near impossible for my expertise.

Uhhh, it's alright. How about this one. 

> @dotjaz try this one out https://github.com/USBhost/MX_FFmpeg/releases/tag/1.35.0_test

There, can you compile it? At least neon and arm64 only.

**Comment by USBhost** [comment]
> > Sadly I do not believe we can. I tried in the past and well it didn't work out so well. Also MX player has alot of custom patches and closed source binary blobs making any kind of porting near impossible for my expertise.
> 
> Uhhh, it's alright. How about this one.
> 
> > @dotjaz try this one out https://github.com/USBhost/MX_FFmpeg/releases/tag/1.35.0_test
> 
> There, can you compile it? At least neon and arm64 only.

That's what I meant as tried. I do not believe it actually did anything. But I can compile it again
