### ISSUE TITLE
AC4 Support

### ISSUE THREAD

**Issue by Theitfixer85** [USBhost/MX_FFmpeg#9]
Is it possible to release a beta codec pack for mxplayer with ac4 support?

There is an experimental build of ffmpeg which now supports AC4

The tree for this can be found
https://github.com/richardpl/FFmpeg/tree/ac4

**Comment by USBhost** [comment]
MX uses a modified ffmpeg source. I can only use what is provided and I cannot cherry pick the changes for they are not documented.

Also don't keep your hopes too high as MX updates ffmpeg every half a year or so.
